### ISSUE TITLE
Gingerbread OMAP kernel?

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [MotorolaMobilityLLC/kernel-omap#1]
Does Motorola still have the Android 2.3.6 Gingerbread kernel for OMAP devices (the XT860 to be specific)? I work with older devices and I'd like the kernel for this phone.

**Comment by Lost-Entrepreneur439** [comment]
@asbraga-motorola, someone told me i had to mention you for the kernel source to be shared

**Comment by asbraga-motorola** [comment]
It's quite an old product, I will check if we still have its kernel source.

**Comment by asbraga-motorola** [comment]
I have got this code for OMAP Gingerbread, hope it helps:
https://github.com/MotorolaMobilityLLC/kernel-omap/releases/tag/MMI-stable-dev5-targa-solana-le
